fix: 프론트엔드, 백엔드 스크립트가 항상 둘 다 실행되던 문제 수정

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -16,33 +16,35 @@ backend_files=$(echo "$files" | grep -E "^backend/.*\.(java|xml|properties)$") |
 
 #################### 프론트엔드 스크립트 ####################
 
-# eslint 실행을 위해 frontend 폴더로 이동
-cd frontend
-
-echo "[pre-commit] ⏳ Checking lint for staged files..."
-
-# Lint fix 실행
 if [ -n "$frontend_files" ]; then
+  # eslint 실행을 위해 frontend 폴더로 이동
+  cd frontend
+
+  echo "[pre-commit] ⏳ Checking lint for staged files..."
+  # Lint fix 실행
   echo "[pre-commit] Running Lint..."
   pnpm exec eslint --fix $frontend_files
 
   # Lint로 fix된 파일들을 다시 스테이징
   echo "[pre-commit] Staging fixed files..."
   echo "$frontend_files" | xargs git add
+
+  # Lint 검사
+  if ! pnpm exec eslint $frontend_files; then
+    echo "[pre-commit] ❌ Lint check failed. Commit aborted."
+    exit 1
+  fi
 fi
 
-# Lint 검사
-if ! pnpm exec eslint $frontend_files; then
-  echo "[pre-commit] ❌ Lint check failed. Commit aborted."
-  exit 1
-fi
 
 
 #################### 백엔드 스크립트 ####################
 
-cd backend
+if [ -n "$backend_files" ]; then
+  cd backend
 
-
+  # Do something
+fi
 
 
 #################### 성공 분기 ####################
diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -33,32 +33,36 @@ fi
 
 #################### 프론트엔드 스크립트 ####################
 
-# pnpm 실행을 위해 frontend 폴더로 이동
-cd frontend
+if [ -n "$frontend_files" ]; then
+  # pnpm 실행을 위해 frontend 폴더로 이동
+  cd frontend
 
-# pnpm run build 성공 여부 검사
-if ! pnpm run build; then
-  echo "[pre-push] ❌ Error: Build failed. Push aborted."
-  exit 1
+  # pnpm run build 성공 여부 검사
+  if ! pnpm run build; then
+    echo "[pre-push] ❌ Error: Build failed. Push aborted."
+    exit 1
+  fi
+  # # pnpm run test 성공 여부 검사
+  # if ! pnpm run test; then
+  #   echo "[pre-push] ❌ Tests failed. Push aborted."
+  #   exit 1
+  # fi
+  
+  # # 민감한 정보 패턴 검사 (credentials, API keys, etc.)
+  # sensitive_patterns="(AWS_ACCESS_KEY_ID|SECRET|PASSWORD)"
+  # if git diff --cached | grep -E "$sensitive_patterns"; then
+  #   echo "[pre-push] ❌ Sensitive information detected in changes. Push aborted."
+  #   exit 1
+  # fi
 fi
-
-# # pnpm run test 성공 여부 검사
-# if ! pnpm run test; then
-#   echo "[pre-push] ❌ Tests failed. Push aborted."
-#   exit 1
-# fi
-
-# # 민감한 정보 패턴 검사 (credentials, API keys, etc.)
-# sensitive_patterns="(AWS_ACCESS_KEY_ID|SECRET|PASSWORD)"
-# if git diff --cached | grep -E "$sensitive_patterns"; then
-#   echo "[pre-push] ❌ Sensitive information detected in changes. Push aborted."
-#   exit 1
-# fi
 
 #################### 백엔드 스크립트 ####################
 
-cd backend
+if [ -n "$backend_files" ]; then
+  cd backend
 
+  # Do something
+fi
 
 
 #################### 성공 분기 ####################
